spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdeskdb
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    root: INFO
    com.ganesh.helpdesk: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
